# Generated by Django 4.2.27 on 2026-03-14 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('flat_or_room', models.CharField(help_text='e.g. Flat 3, Room 2B, Shop 5', max_length=100)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, help_text='Annual rent amount in Naira', max_digits=12)),
                ('agreement_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caution_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenancy_start', models.DateField(blank=True, null=True)),
                ('tenancy_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property', verbose_name='Property')),
            ],
            options={
                'ordering': ['flat_or_room', 'name'],
            },
        ),
    ]
